language: ruby
rvm:
- 2.0.0

addons:
  code_climate:
    repo_token: 792ab6282add3c34a98e894466e2a54e9d66516512d73ebefe8dfa73446a5cee
    
bundler_args: --without development

notifications:
  email:
    recipients:
      - gberdugo@gmail.com
    on_failure: change
    on_success: never